apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nai-nfs-storage
parameters:
  nfsPath: /model_share                   # Change this to your NFS share path
  nfsServer: labFS.ntnxlab.local.         # Change this to your NFS server IP or FQDN
  storageType: NutanixFiles
provisioner: csi.nutanix.com
reclaimPolicy: Delete
volumeBindingMode: Immediate